service: aws-golang-simple-http-endpoint

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
      Resource: 'arn:aws:dynamodb:us-west-2:*:table/Moments'

functions:
  timeline:
    handler: bin/timeline
    events:
      - http:
          path: timeline
          method: post

package:
 exclude:
   - ./**
 include:
   - ./bin/**
