service: timeline

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
        - 'dynamodb:PutItem'
      Resource: 'arn:aws:dynamodb:us-west-2:*:table/Moments'
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource: 'arn:aws:s3:::timeline-moments/*'

functions:
  timeline:
    handler: bin/timeline
    events:
      - http:
          path: timeline
          method: post
  timeline_s3_handler:
    handler: bin/s3_handler
    events:
      - s3:
          bucket: timeline-moments
          event: s3:ObjectCreated:*
          existing: true

package:
 exclude:
   - ./**
 include:
   - ./bin/**
